# Generated by Django 3.2.7 on 2021-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
